development: 
 :address: "smtp.gmail.com"
 :port: 587
 :domain: 'gmail.com'
 :user_name: 'origds@gmail.com'
 :password: 'origds1992'
 :authentication: 'plain'
 :enable_starttls_auto: true 

production:
 :address: "smtp.gmail.com"
 :port: 587
 :domain: 'gmail.com'
 :user_name: 'origds@gmail.com'
 :password: 'origds1992'
 :authentication: 'plain'
 :enable_starttls_auto: true 